services:
  postgres:
    container_name: "postgres"
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: database

  backend:
    container_name: "backend"
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:your_password@postgres:5432/database
    command: >
      sh -c "
        apk add --no-cache openssl &&
        npm install &&
        npm run dev
      "

  frontend:
    container_name: "frontend"
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    command: >
      sh -c "
        npm install &&
        npm run dev
      "

  swagger-editor:
    container_name: "swagger-editor"
    image: swaggerapi/swagger-editor
    ports:
      - "3010:8080"
    depends_on:
      - openapi-generator

  openapi-generator:
    container_name: "openapi-generator"
    image: openapitools/openapi-generator-cli
    working_dir: /docs
    volumes:
      - ./docs/openapi:/docs
    command: >
      generate -i openapi.yml -g markdown -o docs
    depends_on:
      - postgres
      - tbls

  tbls:
    container_name: "tbls"
    image: k1low/tbls
    working_dir: /work
    volumes:
      - ./docs:/work
    command: doc postgresql://user:your_password@postgres:5432/database?sslmode=disable
    depends_on:
      - postgres

  swagger-ui:
    container_name: "swagger-ui"
    image: swaggerapi/swagger-ui
    ports:
      - "3020:8080"
    volumes:
      - ./docs/openapi:/swagger
    environment:
      SWAGGER_JSON: /swagger/openapi.yml
    depends_on:
      - openapi-generator

  swagger-bundle:
    container_name: "swagger-bundle"
    image: jeanberu/swagger-cli
    volumes:
      - ./docs/openapi:/docs
    command: >
      swagger-cli bundle /docs/openapi.yml -t yaml --outfile /docs/bundled.yaml
    depends_on:
      - swagger-ui

  swagger-validate:
    container_name: "swagger-validate"
    image: jeanberu/swagger-cli
    volumes:
      - ./docs/openapi:/docs
    command: >
      swagger-cli validate /docs/openapi.yml
    depends_on:
      - swagger-ui

  swagger-api:
    container_name: "swagger-api"
    image: stoplight/prism:5
    volumes:
      - ./docs/openapi:/swagger
    ports:
      - "3030:4010"
    command: |
      mock -h 0.0.0.0 /swagger/openapi.yml -d
    depends_on:
      - openapi-generator

  stoplight-spectral:
    container_name: "stoplight-spectral"
    image: stoplight/spectral:6
    working_dir: /docs
    volumes:
      - ./docs/openapi:/docs
    command: >
      lint /docs/openapi.yml
    depends_on:
      - swagger-ui

  mkdocs:
    container_name: "mkdocs"
    image: squidfunk/mkdocs-material
    ports:
      - "3040:8000"
    volumes:
      - ./:/docs
    command: >
      serve --dev-addr=0.0.0.0:8000

  studio:
    container_name: "studio"
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:your_password@postgres:5432/database
    command: >
      sh -c "
        apk add --no-cache openssl &&
        npm install &&
        npx prisma studio
      "
