services:
  postgres:
    container_name: "postgres"
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: database

  backend:
    container_name: "backend"
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:your_password@postgres:5432/database
    command: >
      sh -c "
        apk add --no-cache openssl &&
        npm install &&
        npm run dev
      "

  frontend:
    container_name: "frontend"
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    command: >
      sh -c "
        npm install &&
        npm run dev
      "

  tbls:
    image: k1low/tbls
    working_dir: /work
    volumes:
      - ./docs:/work
    command: doc postgresql://user:your_password@postgres:5432/database?sslmode=disable
    depends_on:
      - postgres

  openapi-generator:
    container_name: "openapi-generator"
    image: openapitools/openapi-generator-cli
    volumes:
      - ./docs:/docs
    command: >
      generate -i /docs/openapi.yml -g html2 -o /docs/output

  swagger-editor:
    container_name: "swagger-editor"
    image: swaggerapi/swagger-editor
    ports:
      - "3010:8080"

  swagger-ui:
    container_name: "swagger-ui"
    image: swaggerapi/swagger-ui
    ports:
      - "3020:8080"
    volumes:
      - ./docs:/swagger
    environment:
      SWAGGER_JSON: /swagger/openapi.yml

  swagger-api:
    container_name: "swagger-api"
    image: stoplight/prism:5
    volumes:
      - ./docs:/swagger
    ports:
      - "3030:4010"
    command: |
      mock -h 0.0.0.0 /swagger/openapi.yml -d

  studio:
    container_name: "studio"
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:your_password@postgres:5432/database
    command: >
      sh -c "
        apk add --no-cache openssl &&
        npm install &&
        npx prisma studio
      "
