services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "3010:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "3020:8080"
    volumes:
      - ./:/swagger
    environment:
      SWAGGER_JSON: /swagger/openapi.yml

  swagger-api:
    image: stoplight/prism:4
    container_name: "swagger-api"
    ports:
      - "3030:4010"
    command: mock -h 0.0.0.0 /swagger/openapi.yml -d
    volumes:
      - ./:/swagger
